### ISSUE TITLE
job.task not a function

### ISSUE THREAD

**Issue by joshua1** [Saquib764/node-runner#1]
Hi I am trying to use this library and get this error after the first run (using intervals)
```
/Users/user/Documents/Sycamore labs/AjalaProject/node_modules/node-runnr/node-runnr.js:361
                                                        job.task(null, function(data){
                                                            ^

TypeError: job.task is not a function
```

**Comment by Saquib764** [comment]
You need to pass a job by calling `job` function. Please see the documentation.

**Comment by joshua1** [comment]
@Saquib764 I did. Please see snippet below
```
const Runnr = require('node-runnr');
const newSession = require('./sessions/sessionMethods');

const Jobs = new Runnr();

module.exports = function () {
  // configure cron Jobs
  Jobs.interval('session_create', '50:0')
.job(newSession.createSession())
  .then(result => console.log(result))
.exit(() => console.log('new session create Job exit'));
}
```

**Comment by Saquib764** [comment]
module.exports = function () {
  // configure cron Jobs
  Jobs.interval('session_create', '50:0')
.job(newSession.createSession)
<--- no brackets needed.
  .then(result => console.log(result))
.exit(() => console.log('new session create Job exit'));
}


---------------------------------------------------------------------------------------
Md Saquib Alam
B. Tech, IIT Bombay
9892776105
